[space]
default_app = "zennist"

[board]
initial_count = 3

[[favorite_apps]]
name = "Google Chrome"
exec = "google-chrome-stable --enable-features=UseOzonePlatform --ozone-platform=wayland --disable-gpu"
icon = "/usr/share/icons/hicolor/128x128/apps/google-chrome.png"

[[favorite_apps]]
name="Weston Terminal"
exec="weston-terminal"
icon="/usr/share/weston/terminal.png"

[[favorite_apps]]
name="File Explore"
exec="nautilus"
icon = "/usr/share/icons/hicolor/scalable/apps/org.gnome.Nautilus.svg"

[[favorite_apps]]
name="Blender"
exec="/usr/local/blender-3.4.1-linux-x64/blender --window-geometry 0 0 1000 800"
icon="/usr/local/blender-3.4.1-linux-x64/blender.svg"

[[favorite_apps]]
name="Zen Object Viewer"
exec="zen-object-viewer"
icon="/usr/local/share/zen-object-viewer/assets/icon/3d_viewer_icon.gltf"
disable_2d=true # Do not display in 2D launcher. Default is false.
